eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
server:
  port: 8761
  http2:
    enabled: true
logging:
  file:
    name: eureka-server-1.log
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: info
    '[org.springframework]': debug
spring:
  application:
    name: eureka-server